import LegalPage from "../../components/LegalPage";

export const metadata = {
  title: "Terms of Service — Lodestar",
  description: "The terms for using Lodestar.",
};

export default function Terms() {
  return (
    <LegalPage title="Terms of Service" updated="June 30, 2026">
      <p>
        These terms govern your use of Lodestar, operated by Nomad ("we", "us"). By
        creating an account or using the app, you agree to them. If you do not
        agree, please do not use Lodestar.
      </p>

      <h2>What Lodestar is</h2>
      <p>
        Lodestar is a personal development tool with an AI guide, Vega, that helps
        you turn goals into a daily practice. It is a productivity and motivation
        product, not professional advice. See the next section.
      </p>

      <h2>Not medical, therapy, or professional advice</h2>
      <p>
        <strong>Lodestar and Vega do not provide medical, mental health, legal, or
        financial advice, and are not a substitute for a licensed professional.</strong>{" "}
        Guidance is for general informational and motivational purposes only. If you
        are in crisis, see our <a href="/disclaimer">disclaimer</a> for resources. In
        an emergency, call your local emergency number.
      </p>

      <h2>Eligibility and accounts</h2>
      <p>
        You must be at least 18 years old to use Lodestar. You are responsible for
        the activity on your account and for keeping your sign-in secure.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Do not misuse, overload, probe, or attempt to disrupt the service.</li>
        <li>Do not use Lodestar for anything unlawful or harmful to others.</li>
        <li>Do not attempt to extract another member's data.</li>
      </ul>

      <h2>AI limitations</h2>
      <p>
        Vega's responses are generated by AI and may be imperfect or incomplete. Use
        your own judgment, and do not rely on them for decisions that need a
        qualified professional.
      </p>

      <h2>Subscriptions and billing</h2>
      <p>
        Lodestar offers a free tier and may offer paid plans. If you purchase a paid
        plan, the price, billing period, and renewal terms are shown at checkout.
        Where purchases are made through an app store, that store's terms and refund
        policies also apply.
      </p>

      <h2>Your content</h2>
      <p>
        You own the entries and Life Map you create. You grant us the limited
        permission needed to store and process your content to operate the service,
        including sending it to our AI provider to generate your results.
      </p>

      <h2>Termination</h2>
      <p>
        You may stop using Lodestar at any time and request deletion of your account.
        We may suspend or end access if these terms are violated or to protect the
        service and its members.
      </p>

      <h2>Disclaimers and limitation of liability</h2>
      <p>
        Lodestar is provided "as is" without warranties of any kind. To the fullest
        extent permitted by law, we are not liable for indirect, incidental, or
        consequential damages, or for outcomes that depend on your own actions and
        circumstances.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms as the product evolves. Continued use after an
        update means you accept the revised terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms: <a href="mailto:nomadconsulting7@gmail.com">nomadconsulting7@gmail.com</a>.
      </p>
    </LegalPage>
  );
}
